version: 2.1

jobs:
  run_php_tests:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run:
          command: |
            composer run all-checks-strict
          name: Run all checks (PHP 7.4)
  notify_slack:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run:
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"New PHPCS Config Release","blocks":[{"type":"header","text":{"type":"plain_text","text":"New PHPCS Config Release"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Version:* <https://github.com/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/releases/tag/'${CIRCLE_TAG}'|'${CIRCLE_TAG}'>"},{"type":"mrkdwn","text":"<https://github.com/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/issues|Issues> *|* <https://github.com/'${CIRCLE_PROJECT_USERNAME}'/'${CIRCLE_PROJECT_REPONAME}'/pulls|Pull Requests>"}]}]}' ${SLACK_WEBHOOK}
          name: Send Slack update to channel

workflows:
  run_tests:
    jobs:
      - run_php_tests
  run_notify_slack:
    jobs:
      - notify_slack:
          filters:
            tags:
              only: /v?[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha).[0-9]+)?/
            branches:
              ignore: /.*/
